### ISSUE TITLE
Add a button for copying the permalink

### ISSUE THREAD

**Issue by christophberger** [quasilyte/gopherkon#5]
The URL already adapts to the current state of the gopher, but a "copy URL" button would add a tick more convenience.

**Comment by quasilyte** [comment]
Is this something you are looking for?
![image](https://user-images.githubusercontent.com/6286655/54784889-f6da7380-4c35-11e9-86e0-89776f0b45fa.png)

**Comment by christophberger** [comment]
Oh, yes exactly! Now that was quick!

**Comment by quasilyte** [comment]
Glad to hear that. :)
